### ISSUE TITLE
[DOCS] add pointer to documentation describing how to project new scRNA data onto this nomenclature? 

### ISSUE THREAD

**Issue by alexlenail** [AllenInstitute/nomenclature#4]
I'm not sure how to use this nomenclature with my fresh 10X data.

**Comment by jeremymiller** [comment]
Thanks for posting an issue.  This package cannot be used directly on fresh 10X data, but rather is intended to be used after clustering and annotation.  There are many options for clustering, but for annotation I would recommend [Azimuth](https://azimuth.hubmapconsortium.org/), if the tissue you are using is one of tissues included in this tool.  After these steps, you should then apply this nomenclature library to assign standard tags to your data and output taxonomy files in standard format.  If you happen to be studying mammalian neocortex, I would recommend using the terms from the BICCN (see Extended Data Table 2 and Supplementary Table 2 [in this paper](https://www.nature.com/articles/s41586-021-03950-0)).
